### ISSUE TITLE
[BUG] Crash when joining server related to terraform boat data tracking

### ISSUE THREAD

**Issue by Thepigcat76** [Cristelknight999/DoAPI#33]
### What mod appears to be problematic?

🧀 Meadow

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is the mod running in an unstable environment?

- [X] I am using a supported modloader (Forge, Fabric, Quilt)
- [ ] I have self built the mod
- [ ] This is running in a dev environment

### Current Behavior

When joining a server my friend encountered this issue. We were able to resolve it by teleporting him away. The issue seems to be related to this line of terraform boat data tracking <https://github.com/Team-Let-s-Do/DoAPI/blob/1.20/forge/src/main/java/de/cristelknight/doapi/forge/terraform/boat/impl/TerraformBoatTrackedData.java#L22>

### Expected Behavior

Be able to join the server regularly

### Steps To Reproduce

No idea honestly, the crash appeared out of nowhere.

### Relevant log output

```shell
[20:14:13] [Netty Client IO #1/ERROR]: Exception caught in connection handler!
 java.lang.IndexOutOfBoundsException: index: 9, length: 841 (expected: range(0, 30))
	at MC-BOOTSTRAP/io.netty.buffer@4.1.82.Final/io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390)
	at MC-BOOTSTRAP/io.netty.buffer@4.1.82.Final/io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397)
	at MC-BOOTSTRAP/io.netty.buffer@4.1.82.Final/io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1384)
	at MC-BOOTSTRAP/io.netty.buffer@4.1.82.Final/io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:481)
	at MC-BOOTSTRAP/io.netty.buffer@4.1.82.Final/io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:130)
	at MC-BOOTSTRAP/io.netty.buffer@4.1.82.Final/io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1270)
	at MC-BOOTSTRAP/io.netty.buffer@4.1.82.Final/io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.FriendlyByteBuf.toString(FriendlyByteBuf.java:1537)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.FriendlyByteBuf.m_130136_(FriendlyByteBuf.java:676)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.FriendlyByteBuf.m_130281_(FriendlyByteBuf.java:711)
	at TRANSFORMER/doapi@1.2.15/de.cristelknight.doapi.forge.terraform.boat.impl.TerraformBoatTrackedData.read(TerraformBoatTrackedData.java:22)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.FriendlyByteBuf.m_236860_(FriendlyByteBuf.java:316)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.FriendlyByteBuf$Reader.m_236877_(FriendlyByteBuf.java:1588)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.syncher.EntityDataSerializer$1.m_6709_(EntityDataSerializer.java:35)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.syncher.SynchedEntityData$DataValue.m_252951_(SynchedEntityData.java:284)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.syncher.SynchedEntityData$DataValue.m_252860_(SynchedEntityData.java:279)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.m_252908_(ClientboundSetEntityDataPacket.java:32)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.<init>(ClientboundSetEntityDataPacket.java:16)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.ConnectionProtocol$PacketSet.m_178327_(ConnectionProtocol.java:459)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.ConnectionProtocol.m_178321_(ConnectionProtocol.java:522)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:32)
	at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
	at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
	at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.handler@4.1.82.Final/io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### What modloader are you running the mod on?

Forge

### Anything else?

[latest(1).log](https://github.com/user-attachments/files/16460588/latest.1.log)

**Comment by Thepigcat76** [comment]
Seems to be an issue caused by mowzies mobs
